apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
        - name: frontendapp
          image: ducanh68/frontend
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
spec:
  selector:
    app: frontendapp
  type: LoadBalancer
  ports:
    - name: frontendapp
      protocol: TCP
      port: 80
      targetPort: 5000