apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ducanh68/order-service
---
apiVersion: v1
kind: Service
metadata:
  name: service-order
spec:
  selector:
    app: order
  type: LoadBalancer
  ports:
    - name: order
      protocol: TCP
      port: 5003
      targetPort: 5003